modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]]
modId="virg0m0d"
version="${file.jarVersion}"
displayName="Example Mod" #mandatory
logoFile="examplemod.png" #optional
credits="Thanks for this example mod goes to Java"
authors="Groxhomer, Mauro1233, FrancoCraft, RaYMarK_, Mrslucas"
description='''

Pendiente


'''

[[dependencies.virg0m0d]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.virg0m0d]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
